---
galaxy_info:
  author: Jay Stockhausen
  description: Tailscale VPN installation and configuration
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - tailscale
    - vpn
    - networking
    - security

dependencies: []
